doctrine:
    dbal:
        driver: pdo_pgsql
        user: '%env(resolve:PG_DATABASE_USER)%'
        host: '%env(resolve:PG_DATABASE_HOST)%'
        password: '%env(resolve:PG_DATABASE_PASSWORD)%'
        dbname: '%env(resolve:PG_DATABASE_NAME)%'
        sslmode: '%env(resolve:PG_DATABASE_SSL_MODE)%'
        server_version: '%env(resolve:PG_DATABASE_SERVER_VERSION)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        mappings:
            postgres:
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                is_bundle: false
                type: annotation
                alias: postgres
        naming_strategy: doctrine.orm.naming_strategy.underscore