debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
[retry]
[docker]
watch = true
exposedbydefault = false
[traefikLog]
filePath = "log/error.log"
[accessLog]
filePath = "log/access.log"
